# Generated by Django 2.2.28 on 2026-03-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20260306_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ttitle',
            new_name='title',
        ),
    ]
