# Generated by Django 2.2.28 on 2026-03-24 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20260306_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('accountType', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], default='customer', max_length=50)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventphoto',
            options={'ordering': ['order'], 'verbose_name': 'Event Photo', 'verbose_name_plural': 'Event Photos'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='reviewCount',
        ),
        migrations.AlterField(
            model_name='business',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Account'),
        ),
        migrations.AlterField(
            model_name='business',
            name='displayName',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='The display name must be at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('accountId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Account')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='The display name must be at least 2 characters')])),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('businessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'unique_together': {('customerId', 'businessId')},
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'unique_together': {('customerId', 'eventId')},
            },
        ),
    ]
